### PR TITLE
Shiny pokemon image bug fix

### LINKED ISSUE #27: shiny pokemon image is missing?
#### Describe The Bug
shiny pokemon image is missing.

#### To Reproduce
open pokemon detail, in that page there is carousel which show pokemon images, but somehow shiny images is missing. I think the response from the API changed.
API : https://pokeapi.co/

#### Expected Behavior
shiny images shown as well.

#### Screenshots
shiny image not shown
image

normal image is shown
image

### PR DESCRIPTION
**Pull request by SebaCaste**
## Shiny-image-fix

Filtered undesired data from api response, fixing issue #27

### CODE REVIEW

File: src/pages/DetailPages/index.js [hunk 1]
```diff
@@ -34,7 +34,7 @@ function DetailPages(props) {
       for (const key in sprites) {
         const altText = formatCarouselCaption(key);
         const src = sprites[key];
-        if (altText && src) {
+        if (altText && src && key !== "versions" && key !== "other" ) {
```
Comment (ryananjasmara) [inline src/pages/DetailPages/index.js:37]: so the response change the `key` huh, well this might do the fix, but still shiny image is missing.

**Comment by ryananjasmara** [comment]
this PR might fix the broken images, i will track the API response later. anyway thanks for helping @SebaCaste
